### ISSUE TITLE
Make number of volumes configurable

### ISSUE THREAD

**Issue by DiamondDragon** [GodelTech/CodeReview.Orchestrator#26]
#### DESCRIPTION
Orchestrator uses now tree predefined volumes:

* artifacts
* src
* imports

It's suggested to make number of volumes configurable. 

#### ADDITIONAL CONTEXT
One of possible options is to introduce separate section named `volumes` and define volume information in this section:

```yaml

variables: 
  srcPath: /src
volumes:
   src:
      folderToImport: ./src
      readOnly: false
      targetFolder: /src
   artifacts:
      folderToOutput: ./output
   imports:
      folderToImport: ./imports
      readOnly: true
      targetFolder: /imports

activities:
  git:
    image: godeltech/codereview.tools.gitprovider
    environment:
      GIT_REPOSITORY_URL: https://github.com/GodelTech/CodeReview.Orchestrator.git
      GIT_BRANCH: main
    volumes:
      sources: ...

```

**NOTE:** The only breaking change might be a need to explicitly specify target folder path if operating system for activity differs from default.
